---
title: "Paper Figures ggplot"
output: html_document
date: '2024-12-14'
---

```{r}
library(ggplot2)
source("/project2/mstephens/yunqiyang/surv-susie/survival-susie/code/pip.R")
```

```{r}
# GTEx simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/susie.rds")
svb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/svb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/bvsnlp.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/r2b.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/rss.rds")

indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.svb = unlist(lapply(indx, function(x) svb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$rss.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))

dat.gtex <- list()
dat.gtex[[1]] <- pip.susie
dat.gtex[[2]] <- pip.svb
dat.gtex[[3]] <- pip.bvsnlp
dat.gtex[[4]] <- pip.r2b
dat.gtex[[5]] <- pip.rss
dat.gtex[[6]] <- is_effect
names(dat.gtex) = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "R2BGLiMS", "SuSiE.RSS", "is_effect")


# UKB simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/r2b.rds")

indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.svb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))


dat.ukb <- list()
dat.ukb[[1]] <- pip.susie
dat.ukb[[2]] <- pip.svb
dat.ukb[[3]] <- pip.bvsnlp
dat.ukb[[4]] <- pip.r2b
dat.ukb[[5]] <- pip.rss
dat.ukb[[6]] <- is_effect
names(dat.ukb) = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "R2BGLiMS", "SuSiE.RSS", "is_effect")
```


### 1. PIP distribution plot
```{r}
# Combined function for PIP comparison
prepare_pip_data <- function(pip1, pip2, is_effect, method, simulation) {
  data.frame(
    pip1 = pip1,
    pip2 = pip2,
    is_effect = is_effect,   # 0 or 1
    method = method,
    simulation = simulation
  )
}
```


```{r}
method = c("survival.svb", "BVSNLP", "R2BGLiMS", "SuSiE.RSS")
pip_data <- NULL
for (i in 1:length(method)){
  m = method[i]
  dat1 <- prepare_pip_data(dat.gtex[['CoxPH-SuSiE']], dat.gtex[[m]], dat.gtex[["is_effect"]], m, "GTEx simulation")
  dat2 <- prepare_pip_data(dat.ukb[['CoxPH-SuSiE']], dat.ukb[[m]], dat.ukb[["is_effect"]], m, "UKB simulation")
  pip_data <- rbind(pip_data, dat1, dat2)
}
```

```{r}
ggplot(pip_data) +
  # Grey dots first
  geom_point(data = subset(pip_data, is_effect == 0), 
             aes(x = pip1, y = pip2), color = "darkgrey", size = 1.25, shape = 1) +
  # Red dots on top
  geom_point(data = subset(pip_data, is_effect == 1), 
             aes(x = pip1, y = pip2), color = "red", size = 0.7) +
  # Blue dashed diagonal line
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "blue") +
  # Facet grid layout with free x scales
  facet_grid(simulation ~ method, scales = "free_x", space = "free_x") +
  # Labels and Theme
  xlab("CoxPH-SuSiE") +
  ylab("PIP") +
  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank(),       # Remove background grid lines
    legend.position = "none"         # Remove legend
  )


ggsave("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/pip_combined_gg.pdf", width = 16, height = 8, dpi = 300)

```

### 2. PIP calibration plot

```{r}
# Function to convert calibration results to a tidy data frame
prepare_calibration_data <- function(calibration, method, simulation) {
  data.frame(
    Expected = calibration[, "expected"],  # Predicted PIP
    Observed = calibration[, "empirical"],    # Observed proportion of effects
    method = method,
    simulation = simulation
  )
}
```

```{r}
method = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "SuSiE.RSS", "R2BGLiMS")
calibration_data <- NULL
for (m in method){
  cali1 <- pip_calibration(dat.gtex[[m]], dat.gtex[["is_effect"]])
  cali2 <- pip_calibration(dat.ukb[[m]], dat.ukb[["is_effect"]])
  
  dat1 <- prepare_calibration_data(cali1, m, "GTEx simulation")
  dat2 <- prepare_calibration_data(cali2, m, "UKB simulation")
  calibration_data <- rbind(calibration_data, dat1, dat2)
}
```

```{r}
ggplot(calibration_data, aes(x = Expected, y = Observed)) +
  geom_point(shape = 16) + 
  geom_abline(slope = 1, intercept = 0, color = "red", linewidth = 0.5, linetype = "dashed") + 
  facet_grid(simulation ~ method) +           # Facet by method (columns only)
  xlab("Mean PIP") +
  ylab("Observed frequency") +
  theme_classic(base_size = 14) +    # Minimalist theme
  theme(
    strip.text = element_text(face = "bold"),   # Bold facet titles
    axis.text = element_text(size = 10),        # Adjust axis text size
    axis.title = element_text(size = 12),       # Adjust axis label size
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5), # Add border
    plot.margin = margin(5, 5, 5, 5),           # Minimal margins
    strip.background = element_blank(),         # Remove background from facet strips
    strip.placement = "outside"                 # Place facet labels outside
  )

ggsave("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/pip_calibration_combined_gg.pdf", width = 16, height = 8, dpi = 300)


```

```{r}
ggplot(calibration_data, aes(x = Expected, y = Observed)) +
  geom_point(color = "red", size = 1) +  
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "blue") + # Diagonal line x = y
  facet_grid(simulation ~ method) +      # Rows: Simulation, Columns: Method
  xlab("Predicted PIP") +
  ylab("Observed Proportion") +
  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank(),       # Remove grid lines
    axis.text.x = element_text(size = 10), # Adjust x-axis text size
    axis.text.y = element_text(size = 10)
  )


# Save a wider version of the plot
#ggsave("calibration_plots_wide.png", width = 14, height = 6, dpi = 300)

```

```{r}
calibration.susie = pip_calibration(pip.susie, is_effect)
calibration.susie = pip_calibration(pip.susie, is_effect)
calibration.susie = pip_calibration(pip.susie, is_effect)
calibration.susie = pip_calibration(pip.susie, is_effect)
calibration.susie = pip_calibration(pip.susie, is_effect)

# GTEx Simulation
calibration_data <- rbind(
  prepare_calibration_data(calibration.susie, "CoxPH-SuSiE", "GTEx simulation"),
  prepare_calibration_data(calibration.survsvb, "survival.svb", "GTEx simulation"),
  prepare_calibration_data(calibration.bvsnlp, "BVSNLP", "GTEx simulation"),
  prepare_calibration_data(calibration.rss, "SuSiE.RSS", "GTEx simulation"),
  prepare_calibration_data(calibration.r2b, "R2BGLiMS", "GTEx simulation")
)

# UKB Simulation
calibration_data <- rbind(
  calibration_data,
  prepare_calibration_data(pip_calibration(pip.susie, is_effect), "CoxPH-SuSiE", "UKB simulation"),
  prepare_calibration_data(pip_calibration(pip.survsvb, is_effect), "survival.svb", "UKB simulation"),
  prepare_calibration_data(pip_calibration(pip.bvsnlp, is_effect), "BVSNLP", "UKB simulation"),
  prepare_calibration_data(pip_calibration(pip.rss, is_effect), "SuSiE.RSS", "UKB simulation"),
  prepare_calibration_data(pip_calibration(pip.r2b, is_effect), "R2BGLiMS", "UKB simulation")
)

# ggplot2 Calibration Plot
ggplot(calibration_data, aes(x = predicted, y = observed)) +
  geom_point(color = "red", size = 1) +  # Red dots for observed points
  geom_line(aes(x = predicted, y = predicted), linetype = "dashed", color = "blue") +
  facet_grid(simulation ~ method) +      # Rows: Simulation, Columns: Method
  xlab("Predicted PIP") +
  ylab("Observed Proportion") +
  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank(),       # Remove grid lines
    axis.text.x = element_text(size = 10), # Adjust x-axis text size
    axis.text.y = element_text(size = 10)
  )

# Save a wider version of the plot
ggsave("calibration_plots_wide.png", width = 14, height = 6, dpi = 300)

```


```{r}
source("/project2/mstephens/yunqiyang/surv-susie/survival-susie/code/post_summary.R")

pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/fdr_combined.pdf", height = 6, width = 10)
par(mfrow = c(1,2))
# GTEx 
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/susie.rds")
svb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/svb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/bvsnlp.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/r2b.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/rss.rds")

indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) svb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))
  
ts = seq(from = 0, to = 1, by = 0.01)
res.susie = calculate_tpr_vs_fdr(pip.susie, is_effect, ts)
res.svb = calculate_tpr_vs_fdr(pip.survsvb, is_effect, ts)
res.bvsnlp = calculate_tpr_vs_fdr(pip.bvsnlp, is_effect, ts)
res.rss = calculate_tpr_vs_fdr(pip.rss, is_effect, ts)
res.r2b = calculate_tpr_vs_fdr(pip.r2b, is_effect, ts)
  
plot(res.susie[,2], res.susie[,1], type = "l", xlim = c(0,1), ylim = c(0, 1), xlab = "FDR", ylab = "Power",
       main = "GTEx simulation")
lines(res.svb[,2], res.svb[,1], type = "l", col = 2)
lines(res.bvsnlp[,2], res.bvsnlp[,1], type = "l", col = 3)
lines(res.rss[,2], res.rss[,1], type = "l", col = 4)
lines(res.r2b[,2], res.r2b[,1], type = "l", col = 5)
  
points(res.susie[96,2], res.susie[96, 1])
points(res.svb[96,2], res.svb[96, 1])
points(res.bvsnlp[96,2], res.bvsnlp[96, 1])
points(res.rss[96,2], res.rss[96, 1])
points(res.r2b[96,2], res.r2b[96, 1])
  
legend("topleft", legend = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "SuSiE.RSS", "R2BGLiMS"), col = c(1,2,3,4,5), lty = 1)


# UKB
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/r2b.rds")


indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))
  
ts = seq(from = 0, to = 1, by = 0.01)
res.susie = calculate_tpr_vs_fdr(pip.susie, is_effect, ts)
res.svb = calculate_tpr_vs_fdr(pip.survsvb, is_effect, ts)
res.bvsnlp = calculate_tpr_vs_fdr(pip.bvsnlp, is_effect, ts)
res.rss = calculate_tpr_vs_fdr(pip.rss, is_effect, ts)
res.r2b = calculate_tpr_vs_fdr(pip.r2b, is_effect, ts)
  
plot(res.susie[,2], res.susie[,1], type = "l", xlim = c(0,1), ylim = c(0, 1), xlab = "FDR", ylab = "Power",
       main = "UKB simulation")
lines(res.svb[,2], res.svb[,1], type = "l", col = 2)
lines(res.bvsnlp[,2], res.bvsnlp[,1], type = "l", col = 3)
lines(res.rss[,2], res.rss[,1], type = "l", col = 4)
lines(res.r2b[,2], res.r2b[,1], type = "l", col = 5)
  
points(res.susie[96,2], res.susie[96, 1])
points(res.svb[96,2], res.svb[96, 1])
points(res.bvsnlp[96,2], res.bvsnlp[96, 1])
points(res.rss[96,2], res.rss[96, 1])
points(res.r2b[96,2], res.r2b[96, 1])
  
legend("topleft", legend = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "SuSiE.RSS", "R2BGLiMS"), col = c(1,2,3,4,5), lty = 1)


```

