---
title: "Untitled"
output: html_document
date: '2024-10-04'
---

```{r}
source("/project2/mstephens/yunqiyang/surv-susie/survival-susie/code/pip.R")
```

```{r}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/pip_combined.pdf", height = 8, width = 16)
par(mfrow = c(2,4))

# GTEx simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/susie.rds")
svb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/svb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/bvsnlp.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/r2b.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/rss.rds")

indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.svb = unlist(lapply(indx, function(x) svb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$rss.pip[[x]]))
  
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))

res.pip = compare_pip(pip.susie, pip.svb, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "survival.svb"), main = "GTEx simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.bvsnlp, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "BVSNLP"), main = "GTEx simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.r2b, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "R2BGLiMS"), main = "GTEx simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.rss, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "SuSiE.RSS"), main = "GTEx simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")


# UKB simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/r2b.rds")


indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.svb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
  
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))

res.pip = compare_pip(pip.susie, pip.svb, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "survival.svb"), main = "UKB simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.bvsnlp, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "BVSNLP"), main = "UKB simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.r2b, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "R2BGLiMS"), main = "UKB simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  
res.pip = compare_pip(pip.susie, pip.rss, is_effect)
plot_pip(res.pip, labs = c("CoxPH-SuSiE", "SuSiE.RSS"), main = "UKB simulation")
abline(a = 0, b = 1, lty = 2, col = "blue")
  

```

```{r}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/pip_calibration_combined.pdf", height = 8, width = 20)
par(mfrow = c(2,5))

# GTEx simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/susie.rds")
svb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/svb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/bvsnlp.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/r2b.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/rss.rds")

indx = which(bvsnlp$simulate.cor_type == "real")
is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) svb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  
# Calibration plot for pip.susie
calibration.susie = pip_calibration(pip.susie, is_effect)
plot_calibration(calibration.susie, main = "CoxPH-SuSiE")
  
# Calibration plot for pip.svb
calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
plot_calibration(calibration.survsvb, main = "survival.svb")
  
# Calibration plot for pip.bvsnlp
calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
plot_calibration(calibration.bvsnlp, main = "BVSNLP")
  
# Calibration plot for pip.rss
calibration.rss = pip_calibration(pip.rss, is_effect)
plot_calibration(calibration.rss, main = "SuSiE.RSS")
  
# Calibration plot for pip.r2b
calibration.r2b = pip_calibration(pip.r2b, is_effect)
plot_calibration(calibration.r2b, main = "R2BGLiMS")


# UKB simulation
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/r2b.rds")


indx = which(bvsnlp$simulate.cor_type == "real")
is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  
# Calibration plot for pip.susie
calibration.susie = pip_calibration(pip.susie, is_effect)
plot_calibration(calibration.susie, main = "CoxPH-SuSiE")
  
# Calibration plot for pip.svb
calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
plot_calibration(calibration.survsvb, main = "survival.svb")
  
# Calibration plot for pip.bvsnlp
calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
plot_calibration(calibration.bvsnlp, main = "BVSNLP")
  
# Calibration plot for pip.rss
calibration.rss = pip_calibration(pip.rss, is_effect)
plot_calibration(calibration.rss, main = "SuSiE.RSS")
  
# Calibration plot for pip.r2b
calibration.r2b = pip_calibration(pip.r2b, is_effect)
plot_calibration(calibration.r2b, main = "R2BGLiMS")
```


```{r}
source("/project2/mstephens/yunqiyang/surv-susie/survival-susie/code/post_summary.R")

pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/fdr_combined.pdf", height = 6, width = 10)
par(mfrow = c(1,2))
# GTEx 
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/susie.rds")
svb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/svb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/bvsnlp.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/r2b.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/rss.rds")

indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) svb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))
  
ts = seq(from = 0, to = 1, by = 0.01)
res.susie = calculate_tpr_vs_fdr(pip.susie, is_effect, ts)
res.svb = calculate_tpr_vs_fdr(pip.survsvb, is_effect, ts)
res.bvsnlp = calculate_tpr_vs_fdr(pip.bvsnlp, is_effect, ts)
res.rss = calculate_tpr_vs_fdr(pip.rss, is_effect, ts)
res.r2b = calculate_tpr_vs_fdr(pip.r2b, is_effect, ts)
  
plot(res.susie[,2], res.susie[,1], type = "l", xlim = c(0,1), ylim = c(0, 1), xlab = "FDR", ylab = "Power",
       main = "GTEx simulation")
lines(res.svb[,2], res.svb[,1], type = "l", col = 2)
lines(res.bvsnlp[,2], res.bvsnlp[,1], type = "l", col = 3)
lines(res.rss[,2], res.rss[,1], type = "l", col = 4)
lines(res.r2b[,2], res.r2b[,1], type = "l", col = 5)
  
points(res.susie[96,2], res.susie[96, 1])
points(res.svb[96,2], res.svb[96, 1])
points(res.bvsnlp[96,2], res.bvsnlp[96, 1])
points(res.rss[96,2], res.rss[96, 1])
points(res.r2b[96,2], res.r2b[96, 1])
  
legend("topleft", legend = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "SuSiE.RSS", "R2BGLiMS"), col = c(1,2,3,4,5), lty = 1)


# UKB
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/r2b.rds")


indx = which(susie$simulate.cor_type == "real")
pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))
  
ts = seq(from = 0, to = 1, by = 0.01)
res.susie = calculate_tpr_vs_fdr(pip.susie, is_effect, ts)
res.svb = calculate_tpr_vs_fdr(pip.survsvb, is_effect, ts)
res.bvsnlp = calculate_tpr_vs_fdr(pip.bvsnlp, is_effect, ts)
res.rss = calculate_tpr_vs_fdr(pip.rss, is_effect, ts)
res.r2b = calculate_tpr_vs_fdr(pip.r2b, is_effect, ts)
  
plot(res.susie[,2], res.susie[,1], type = "l", xlim = c(0,1), ylim = c(0, 1), xlab = "FDR", ylab = "Power",
       main = "UKB simulation")
lines(res.svb[,2], res.svb[,1], type = "l", col = 2)
lines(res.bvsnlp[,2], res.bvsnlp[,1], type = "l", col = 3)
lines(res.rss[,2], res.rss[,1], type = "l", col = 4)
lines(res.r2b[,2], res.r2b[,1], type = "l", col = 5)
  
points(res.susie[96,2], res.susie[96, 1])
points(res.svb[96,2], res.svb[96, 1])
points(res.bvsnlp[96,2], res.bvsnlp[96, 1])
points(res.rss[96,2], res.rss[96, 1])
points(res.r2b[96,2], res.r2b[96, 1])
  
legend("topleft", legend = c("CoxPH-SuSiE", "survival.svb", "BVSNLP", "SuSiE.RSS", "R2BGLiMS"), col = c(1,2,3,4,5), lty = 1)


```

