---
title: "Bayes Factor comparison"
output: html_document
date: '2024-07-15'
---


### Description:

Compare different types of Bayes factor under different levels of censoring, minor allele frequency, effect size and sample size. 

1. censoring = 0.00, 0.20, 0.40, 0.60, 0.80, 0.99

2. MAF = 0.001, 0.01, 0.1

3. n = 5000, 50000, 500000

4. b1 = -1， -0.1, -0.01, 0.01, 0.1, 1

5. BFs: 

(a) Numerical BF using Gaussian quadrature, our gold standard. https://yunqiyang0215.github.io/survival-susie/gauss_quad.html

(b) Laplace-MLE BF

(c) Wakefeld BF

(d) Wakefeld BF with zscore from coxph() corrected by saddle point approximation. https://yunqiyang0215.github.io/survival-susie/SPAcox.html

```{r}
library(latex2exp)
```

```{r}
res = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/bf_comparison0712/res_bf.rds")
```


```{r}
dat_list = lapply(1:length(res$DSC), function(x) res$compute_bf.result[[x]])
dat = do.call(rbind, dat_list)
dat2 = cbind(res$simulate.censor_lvl, res$simulate.allele_freq, res$simulate.n, 
             res$simulate.b1, dat)
colnames(dat2)[1:4] = c("censor_lvl", "allele_freq", "n", "b1")
dat2 = as.data.frame(dat2)
```

```{r}
censor_lvl = unique(res$simulate.censor_lvl)
af = unique(res$simulate.allele_freq)
print(censor_lvl)
print(af)
```

```{r fig.width = 14, fig.height=20}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/bf_different_n_large_b.pdf", width = 8, height = 18)
par(mfrow = c(6,3))
for (i in 1:length(censor_lvl)){
  for (j in 1:length(af)){
    indx = which(dat2$censor_lvl == censor_lvl[i] & dat2$allele_freq == af[j] & dat2$b1 == 1)
    diff1 = dat2$lbf.numerical - dat2$lbf.laplace
    diff2 = dat2$lbf.numerical - dat2$lbf.wakefeld
    ymin = min(diff1[indx], diff2[indx]) - 1
    ymax = max(diff1[indx], diff2[indx]) + 1
    plot(dat2$n[indx], diff1[indx], ylim = c(ymin, ymax),
         main = paste0("censor=",censor_lvl[i], ", MAF=", af[j]),
         xlab = "sample size", ylab = "difference in log(BF)", cex = 0.8, pch = 20)
    points(dat2$n[indx], diff2[indx], col = "#00CCFF", cex = 0.8, pch = 20)
    fit = lm(diff2[indx] ~ dat2$n[indx])
    abline(fit, col = "grey", lty = 2) 
    legend("bottomleft", legend = c("log(BF.lp)", 'log(BF.wf)'), col = c(1, "#00CCFF"), pch = 20, cex = 0.8)
  }
}
```

```{r fig.width = 14, fig.height=20}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/bf_different_bhat_small_n.pdf", width = 8, height = 18)
par(mfrow = c(6,3))
for (i in 1:length(censor_lvl)){
  for (j in 1:length(af)){
    indx = which(dat2$censor_lvl == censor_lvl[i] & dat2$allele_freq == af[j] & dat2$n == 5e3)
    diff1 = dat2$lbf.numerical - dat2$lbf.laplace
    diff2 = dat2$lbf.numerical - dat2$lbf.wakefeld
    ymin = min(diff1[indx], diff2[indx]) - 0.5
    ymax = max(diff1[indx], diff2[indx]) + 0.5
    plot(dat2$bhat[indx], diff1[indx], ylim = c(ymin, ymax), xlab = "bhat", ylab = "difference in log(BF)",
         main = paste0("censor=",censor_lvl[i], ", MAF=", af[j]), cex = 0.8, pch = 20)
    points(dat2$bhat[indx], diff2[indx], col = "#00CCFF", cex = 0.8, pch = 20)
    legend("bottomleft", legend = c("log(BF.lp)", 'log(BF.wf)'), col = c(1, "#00CCFF"), pch = 20, cex = 0.8)
  }
}

```

```{r fig.width = 14, fig.height=20}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/bf_different_bhat_large_n.pdf", width = 8, height = 18)
par(mfrow = c(6,3))
for (i in 1:length(censor_lvl)){
  for (j in 1:length(af)){
    indx = which(dat2$censor_lvl == censor_lvl[i] & dat2$allele_freq == af[j] & dat2$n == 5e5)
    diff1 = dat2$lbf.numerical - dat2$lbf.laplace
    diff2 = dat2$lbf.numerical - dat2$lbf.wakefeld
    ymin = min(diff1[indx], diff2[indx]) - 0.5
    ymax = max(diff1[indx], diff2[indx]) + 0.5
    plot(dat2$bhat[indx], diff1[indx], ylim = c(ymin, ymax), xlab = "bhat", ylab = "difference in log(BF)",
         main = paste0("censor=",censor_lvl[i], ", MAF=", af[j]), cex = 0.8, pch = 20)
    points(dat2$bhat[indx], diff2[indx], col = "#00CCFF", cex = 0.8, pch = 20)
    legend("bottomleft", legend = c("log(BF.lp)", 'log(BF.wf)'), col = c(1, "#00CCFF"), pch = 20, cex = 0.8)
  }
}

```


```{r fig.width = 12, fig.height=5}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/bf_comparison_b_0.1_n_500000.pdf", width = 8, height = 18)
par(mfrow = c(6,3))

for (i in 1:length(censor_lvl)){
  for (j in 1:length(af)){
    indx = which(res$simulate.censor_lvl == censor_lvl[i] & res$simulate.allele_freq == af[j]
                 & res$simulate.n == 5e5 & res$simulate.b1 == 0.1)
    dat = t(sapply(indx, function(x) res$compute_bf.result[[x]]))
    plot(x = dat[, 'lbf.numerical'], y = dat[, 'lbf.laplace'], pch = 20, main = paste0("censor=",censor_lvl[i], ", MAF=", af[j]),
         ylim = c(min(dat[,c(4:6)])-1, max(dat[, c(4:6)])+1), cex = 0.8,
         xlab = TeX("$log_{10}$(BF.gh)"), ylab = TeX("Other $log_{10}$(BFs)"))
    points(dat[, 'lbf.numerical'], dat[,'lbf.wakefeld'], col = "#26B300", pch = 20, cex = 0.8)
    abline(a = 0, b = 1, col = "grey")
    legend("topleft", legend = c(TeX("$log_{10}$(BF.lp)"), TeX("$log_{10}$(BF.wf)")), col = c(1, "#26B300"), pch = 20, cex = 0.8)
  }
}
```

```{r fig.width = 12, fig.height=5}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/bf_comparison_b_0.01_n_500000.pdf", width = 8, height = 18)
par(mfrow = c(6,3))

for (i in 1:length(censor_lvl)){
  for (j in 1:length(af)){
    indx = which(res$simulate.censor_lvl == censor_lvl[i] & res$simulate.allele_freq == af[j]
                 & res$simulate.n == 5e5 & res$simulate.b1 == 0.01)
    dat = t(sapply(indx, function(x) res$compute_bf.result[[x]]))
    plot(x = dat[, 'lbf.numerical'], y = dat[, 'lbf.laplace'], pch = 20, main = paste0("censor=",censor_lvl[i], ", MAF=", af[j]),
         ylim = c(min(dat[,c(4:6)])-1, max(dat[,c(4:6)])+1), cex = 0.8,
         xlab = TeX("$log_{10}$(BF.gh)"), ylab = TeX("Other $log_{10}$(BFs)"))
    points(dat[, 'lbf.numerical'], dat[,'lbf.wakefeld'], col = "#26B300", pch = 20, cex = 0.8)
    abline(a = 0, b = 1, col = "grey")
    legend("topleft", legend = c(TeX("$log_{10}$(BF.lp)"), TeX("$log_{10}$(BF.wf)")), col = c(1, "#26B300"), pch = 20, cex = 0.8)
  }
}
```

```{r}
dat.sub = dat2[dat2$censor_lvl == 0 & dat2$n == 5e5 & dat2$allele_freq == 0.1, ]
```

```{r fig.width=8, fig.height=6}
par(mfrow = c(2,2))
hist(dat.sub$zscore[dat.sub$b1 == -1], xlab = "zscore", main = "true b = -1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$zscore[dat.sub$b1 == 1],  xlab = "zscore", main = "true b = 1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$bhat[dat.sub$b1 == -1], xlab = "bhat", main = "true b = -1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$bhat[dat.sub$b1 == 1], xlab = "bhat", main = "true b = 1; MAF = 0.1; n = 5e5; no censor")
```

```{r fig.width=8, fig.height=6}
par(mfrow = c(2,2))
hist(dat.sub$lbf.numerical[dat.sub$b1 == -1],  xlab = "log(BF.numerical)", main = "true b = -1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$lbf.numerical[dat.sub$b1 == 1],  xlab = "log(BF.numerical)", main = "true b = 1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$lbf.wakefeld[dat.sub$b1 == -1],  xlab = "log(BF.wakefield)", main = "true b = -1; MAF = 0.1; n = 5e5; no censor")
hist(dat.sub$lbf.wakefeld[dat.sub$b1 == 1],  xlab = "log(BF.wakefield)", main = "true b = 1; MAF = 0.1; n = 5e5; no censor")
```

