---
title: "PIP calibration on large data"
output: html_document
date: '2024-02-20'
---

### Description: the data simulation is described here:

https://yunqiyang0215.github.io/survival-susie/compare_method_large_sample.html

```{r}
pip_calibration <- function(pips, is_effect){
  ts = seq(0, 0.9, by = 0.1)
  res = matrix(NA, ncol = 3, nrow = length(ts))
  colnames(res) = c("range.start", "expected", "empirical")
  for (i in 1:length(ts)){
    lo = ts[i]
    up = lo + 0.1
    indx = which(pips >= lo & pips <= up)
    res[i, 1] = lo
    res[i, 2] = mean(pips[indx])
    res[i, 3] = sum(is_effect[indx])/ length(indx)
  }
  # when there is no pip in the certain range
  res2 = na.omit(res)
  return(res2)
}

plot_calibration <- function(dat.calibration, method, num_effect){
  plot(dat.calibration[,2], dat.calibration[,3], xlim = c(0, 1), ylim = c(0, 1),
       main= paste0("Calibration: ", method, ", # effect= ", num_effect), xlab="Expected", ylab="Observed")
  abline(a = 0, b = 1, col = "red")
}
```

```{r}
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie_rss.rds")
```


### 1. Use the real correlation of SNPs

```{r fig.width=12, fig.height = 10}
par(mfrow = c(3,4))
for (num in 1:3){
  indx = which(bvsnlp$simulate.cor_type == "real" & bvsnlp$simulate.num_effect == num)
  is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  
  # Calibration plot for pip.susie
  calibration.susie = pip_calibration(pip.susie, is_effect)
  plot_calibration(calibration.susie, method = "susie", num_effect = num)
  
  # Calibration plot for pip.svb
  calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
  plot_calibration(calibration.survsvb, method = "svb", num_effect = num)
  
  # Calibration plot for pip.bvsnlp
  calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
  plot_calibration(calibration.bvsnlp, method = "bvsnlp", num_effect = num)
  
  # Calibration plot for pip.rss
  calibration.rss = pip_calibration(pip.rss, is_effect)
  plot_calibration(calibration.rss, method = "susie rss", num_effect = num)
  
}

```


### 2. Near independent SNPs

```{r fig.width=12, fig.height = 10}
par(mfrow = c(3,4))
for (num in 1:3){
  indx = which(bvsnlp$simulate.cor_type == "independent" & bvsnlp$simulate.num_effect == num)
  is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  
  # Calibration plot for pip.susie
  calibration.susie = pip_calibration(pip.susie, is_effect)
  plot_calibration(calibration.susie, method = "susie", num_effect = num)
  
  # Calibration plot for pip.svb
  calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
  plot_calibration(calibration.survsvb, method = "svb", num_effect = num)
  
  # Calibration plot for pip.bvsnlp
  calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
  plot_calibration(calibration.bvsnlp, method = "bvsnlp", num_effect = num)
  
  # Calibration plot for pip.rss
  calibration.rss = pip_calibration(pip.rss, is_effect)
  plot_calibration(calibration.rss, method = "susie rss", num_effect = num)
  
}

```
