---
title: "Data application: cancer subtype"
author: "Yunqi Yang"
date: "6/8/2023"
output: html_document
---

```{r}
library(Matrix)
library(pheatmap)
library(My.stepwise)
library(survival)
library(susieR)
library(mvtnorm)
```

```{r helper func}
### helper functions
# Function to calculate log of approximate BF based on Wakefield approximation
# @param z: zscore of the regression coefficient
# @param s: standard deviation of the estimated coefficient
compute_lbf <- function(z, s, prior_variance){
  abf <- sqrt(s^2/(s^2+prior_variance))
  lbf <- log(sqrt(s^2/(s^2+prior_variance))) + z^2/2*(prior_variance/(s^2+prior_variance))
  return(lbf)
}


compute_approx_post_var <- function(z, s, prior_variance){
  post_var <- 1/(1/s^2 + 1/prior_variance)
  return(post_var)
}

# @param post_var: posterior variance
# @param s: standard deviation of the estimated coefficient
# @param bhat: estimated beta effect
compute_approx_post_mean <- function(post_var, s, bhat){
  mu <- post_var/(s^2)*bhat
  return(mu)
}


surv_uni_fun <- function(x, y, o, prior_variance, estimate_intercept = 0, ...){
  fit <- coxph(y~ x + offset(o))
  bhat <- summary(fit)$coefficients[1, 1] # bhat = -alphahat
  sd <- summary(fit)$coefficients[1, 3]
  zscore <- bhat/sd
  lbf <- compute_lbf(zscore, sd, prior_variance)
  lbf.corr <- lbf - bhat^2/sd^2/2+ summary(fit)$logtest[1]/2
  var <- compute_approx_post_var(zscore, sd, prior_variance)
  mu <- compute_approx_post_mean(var, sd, bhat)
  return(list(mu = mu, var=var, lbf=lbf.corr, intercept=0))
}
```

```{r load data}
# yusha's data
data.combined <- readRDS("./data/combined_data_resectable_v2.rds")
### show the pairwise correlation between program signatures
pheatmap(cor(data.combined[, -c(1:6)]), angle_col = 45)
```

```{r}
### pre-processing
data.combined$male <- ifelse(data.combined$sex=="Male", 1, 0)
data.combined$stageIIb <- ifelse(data.combined$stage=="IIb", 1, 0)
data.combined$stageIII <- ifelse(data.combined$stage=="III-higher", 1, 0)
```

### Method 1: stepwise selection
```{r}
fit.surv <- My.stepwise.coxph(Time = "futime", Status = "event", variable.list = colnames(data.combined)[7:32],
                              in.variable = c("age", "male", "stageIIb", "stageIII"), data = data.combined)

```

### Method 2: survival susie
```{r}
devtools::load_all("/Users/nicholeyang/Desktop/logisticsusie")
```

```{r}
fit_coxph <- ser_from_univariate(surv_uni_fun)
#### parameter settings
L = 10
maxiter = 1e3

X = data.combined[, c(5, 7:35)]
X = as.matrix(X)
p = ncol(X)


## Create  survival object
y <- Surv(data.combined$futime, data.combined$event)
fit.susie <- ibss_from_ser(X, y, L = L, prior_variance = 1., prior_weights = rep(1/p, p), tol = 1e-3, maxit = maxiter,
                     estimate_intercept = TRUE, ser_function = fit_coxph)

pip <- logisticsusie:::get_pip(fit.susie$alpha)
effect_estimate <- colSums(fit.susie$alpha * fit.susie$mu)
class(fit.susie) = "susie"
cs <- susie_get_cs(fit.susie, X)
```

```{r}
fit.susie$alpha
```

```{r}
# Set wider margins to accommodate the labels
par(mar = c(7, 4, 3, 3)) 
plot(pip, xaxt = "n", xlab = "")
axis(1, at=1:30, labels=colnames(X), las=2,  cex.axis = 0.7, xlab = "")
```

```{r}
par(mar = c(7, 4, 3, 3)) 
plot(effect_estimate, xaxt = "n", xlab = "", ylab = "Effect size estimate")
axis(1, at=1:30, labels=colnames(X), las=2,  cex.axis = 0.7, xlab = "")
```
```{r}
cs
```

```{r}
fit.susie$prior_vars
```

### Select 20 features and run survival-susie

The pip for near-zero effects are inflated... from ~0.2 to 0.3 now.
```{r}
#### parameter settings
L = 10
maxiter = 1e3

X = data.combined[, c(16:35)]
X = as.matrix(X)
p = ncol(X)


## Create  survival object
y <- Surv(data.combined$futime, data.combined$event)
fit.susie <- ibss_from_ser(X, y, L = L, prior_variance = 1., prior_weights = rep(1/p, p), tol = 1e-3, maxit = maxiter,
                     estimate_intercept = TRUE, ser_function = fit_coxph)

pip <- logisticsusie:::get_pip(fit.susie$alpha)
effect_estimate <- colSums(fit.susie$alpha * fit.susie$mu)
class(fit.susie) = "susie"
cs <- susie_get_cs(fit.susie, X)
```

```{r}
par(mfrow = c(1,2))
plot(pip)
plot(effect_estimate)
```

```{r}
fit.susie$prior_vars
```



### Simulated Gaussian data with p = 30

```{r}
library(mvtnorm)
```

```{r}
set.seed(500)
cmat = cor(data.combined[, -c(1:6)])
n = 400
p = ncol(cmat)
X = rmvnorm(n=n, sigma=cmat, method="chol")
X[, c(25:28)] = ifelse(X[, c(25:28)] > 0, 1, 0)
b = rep(0, p)
effect_indx = sample(1:p, size = 5, replace = FALSE)
b[effect_indx] = rnorm(5, sd = 0.3)
y  = X %*% b + rnorm(n)

```

```{r}
summary(lm(y ~ X[,effect_indx[1]]))
summary(lm(y ~ X[,effect_indx[2]]))
summary(lm(y ~ X[,effect_indx[3]]))
summary(lm(y ~ X[,effect_indx[4]]))
summary(lm(y ~ X[,effect_indx[5]]))
```

```{r}
b
effect_indx
```

```{r fig.width=10, fig.height=6}
par(mfrow = c(1,2))
res <- susie(X,y,L=10)
plot(coef(res)[-1],pch = 20)
plot(res$pip)
```
```{r}
res$sets
```


