---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Background and analysis on coxph model

+ [Example of survival analysis in R](survival_example.html)

+ [Check effect of standardization in coxph model](check_coxph_fit.html)

+ [Check distribution of zscores under the null in coxph](null_model_zscore.html)

+ [Check more property of coxph()](coxph_fit.html)

+ [coxph() NA example](coxph_na.html)

Check Bayes factor

+ [Numerical integration](numerical_integration.html)

+ [Numerical integration: Gaussian Quadrature](gauss_quad.html)

+ [BF comparison](bf_comparison.html)

+ [Compare BF calculation: numerical integration vs. approximated BF](bf_diff.html)

+ [Saddle point approximation using SPAcox](SPAcox.html)


Simulating survival data

+ [Simulate survival data using exponential distribution](sim_survival.html)

+ [Simulate survival data with censoring](sim_survival_with_censoring.html)


Try different methods on simple simulated data:

+ [Susie IBSS](run_ser_simple_dat.html)

+ [survival.svb](survival.svb.html)

+ [bvsnlp](bvsnlp.html)

+ [lasso cox](cox_lasso.html)

+ [bhglm](bhglm.html)


Try different methods on simulated data with censoring:

+ [Time Comparison of susie & bvsnlp](time_comparison.html)

+ [Susie IBSS](ser_censoring_dat.html)

+ [survival.svb](survival.svb_censoring.html)

+ [bvsnlp](bvsnlp_censoring.html)

+ [bhglm](bhglm_censoring.html)

+ [R2BGLiMS](R2BGLiMS.html)


Try variational approximation:

+ [Variational approximation on exponential survival model](vi_exponential.html)

+ [Poisson SER](poisson_ser.html)

Real data simulation: GTEx genotype 2023

+ [Plot PIPs](compare_pip.html)

+ [Power vs. FDR](compare_power_fdr.html)

+ [Data example: susie with poor performance](susie_poor_performance_example.html)

+ [Updated simulation: power vs. FDR](power_fdr2.html)

+ [Version 3 simulation: power vs. FDR](dsc_sim3.html)

+ [Version 4 simulation: power vs. FDR](dsc_sim4.html)

Susie(-rss) results:

+ [Susie rss diagnosis](susierss_failure.html)

+ [Susie vs. susie rss](survival_susierss.html)

+ [Susie convergence criteria](susie.convergence.html)

Real data simulation: GTEx genotype(2024)

+ [10 iteration result: pip](compare_pip_10iter.html)

+ [10 iteration result: power vs. fdr](gtex_10iter.html)

+ [Larger iteration result: pip](compare_pip_500iter.html)

+ [Larger iteration result: power vs. fdr](gtex_500iter.html)

Real data simulation: UKBiobank genotype

+ [PIP Comparison](pip_comparison_large_sample.html)

+ [Power vs. fdr](ukb_10iter.html)

+ [Method comparison](compare_method_large_sample.html)

+ [SuSIE vs. SuSIE-RSS](susierss_large_sample.html)



Data application result:

+ [Cancer subtype](cancer_subtype.html)

+ [Pdac gene expression](pdac_gene_expr.html)

Time benchmark:

+ [coxph_vs_lm](coxph_vs_lm.html)

+ [Per iteration time across methods](time_per_iter.html)

+ [Running time of different methods](time_benchmark.html)
