---
title: "Fit coxph susie on pdac gene expression"
output: html_document
date: '2024-01-31'
---

1. Model fitting script: /project2/mstephens/yunqiyang/surv-susie/realdata/pdac_dat/fit_pdac.R

2. Result: coxph-SuSIE doesn't find out any signal, while bvsnlp finds 2 genes. 



```{r}
library(survival)
library(susieR)
devtools::load_all("/project2/mstephens/yunqiyang/surv-susie/logisticsusie")
res = readRDS("/project2/mstephens/yunqiyang/surv-susie/realdata/pdac_dat/fit_pdac.rds")

dat = readRDS("/project2/mstephens/yunqiyang/surv-susie/realdata/pdac_dat/dat_pdac.rds")
expression = dat[[2]]
```

```{r}
fit.susie = res[[1]]
fit.bvsnlp = res[[2]]

# Susie results
pip <- logisticsusie:::get_pip(fit.susie$alpha)
pip.sorted = sort(pip, decreasing = TRUE)
pip.sorted[1:5]
class(fit.susie) = "susie"
cs <- susie_get_cs(fit.susie, as.matrix(expression))
iter = fit.susie$iter
print(iter)
```

```{r}
# bvsnlp result
p = ncol(expression)
effect_estimate = rep(0, p)
effect_estimate[fit.bvsnlp$HPM] = fit.bvsnlp$beta_hat
pip = fit.bvsnlp$inc_probs
pip.sorted = sort(pip, decreasing = TRUE)
pip.sorted[1:10]
colnames(expression)[effect_estimate != 0]
```

