---
title: "PIP Comparison in large sample"
output: html_document
date: '2024-02-12'
---

### Description:

Compare PIPs using simulated dataset, where $n=50000$ and $p=1000$.

1. susie: maxiter = 10

2. susie.rss: maxiter = 100

3. surv.svb: maxiter = 100

4. r2b: niter = 50

5. bvsnlp: niter = 30


```{r}
source("/project2/mstephens/yunqiyang/surv-susie/survival-susie/code/pip.R")
```


```{r}

susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie.rds")
survsvb = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/survsvb.rds")
bvsnlp = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/bvsnlp.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie_rss.rds")
r2b = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/r2b.rds")

```

```{r}
censor_lvls = unique(susie$simulate.censor_lvl)
```


### 1. Use the real correlation of SNPs

```{r fig.width= 12, fig.height=20}
par(mfrow = c(6,4))
for (i in 1:length(censor_lvls)){
  indx = which(susie$simulate.cor_type == "real" & susie$simulate.censor_lvl == censor_lvls[i])
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.svb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
  
  is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))


  res.pip = compare_pip(pip.susie, pip.svb, is_effect)
  plot_pip(res.pip, labs = c("susie", "survival.svb"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.bvsnlp, is_effect)
  plot_pip(res.pip, labs = c("susie", "bvsnlp"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.r2b, is_effect)
  plot_pip(res.pip, labs = c("susie", "r2b"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.rss, is_effect)
  plot_pip(res.pip, labs = c("susie", "rss"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
}
```

```{r fig.width= 12, fig.height=18}
par(mfrow = c(6,5))
for (i in 1:length(censor_lvls)){
  indx = which(bvsnlp$simulate.cor_type == "real" & bvsnlp$simulate.censor_lvl == censor_lvls[i])
  is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
  pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  
  # Calibration plot for pip.susie
  calibration.susie = pip_calibration(pip.susie, is_effect)
  plot_calibration(calibration.susie, main = paste0("susie: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.svb
  calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
  plot_calibration(calibration.survsvb, main = paste0("svb: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.bvsnlp
  calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
  plot_calibration(calibration.bvsnlp, main = paste0("bvsnlp: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.rss
  calibration.rss = pip_calibration(pip.rss, is_effect)
  plot_calibration(calibration.rss, main = paste0("rss: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.r2b
  calibration.r2b = pip_calibration(pip.r2b, is_effect)
  plot_calibration(calibration.r2b, main = paste0("r2b: censor=", censor_lvls[i]))
}
```



### 2. Near independent SNPs

```{r fig.width= 12, fig.height=20}
par(mfrow = c(6,4))
for (i in 1:length(censor_lvls)){
  indx = which(susie$simulate.cor_type == "independent" & susie$simulate.censor_lvl == censor_lvls[i])
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.svb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
  
  is_effect = unlist(lapply(indx, function(x) susie$simulate.is_effect[[x]]))


  res.pip = compare_pip(pip.susie, pip.svb, is_effect)
  plot_pip(res.pip, labs = c("susie", "survival.svb"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.bvsnlp, is_effect)
  plot_pip(res.pip, labs = c("susie", "bvsnlp"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.r2b, is_effect)
  plot_pip(res.pip, labs = c("susie", "r2b"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
  res.pip = compare_pip(pip.susie, pip.rss, is_effect)
  plot_pip(res.pip, labs = c("susie", "rss"), main = paste0("censor=",censor_lvls[i]))
  abline(a = 0, b = 1, lty = 2, col = "blue")
  
}
```

```{r fig.width= 12, fig.height=18}
par(mfrow = c(6,5))
for (i in 1:length(censor_lvls)){
  indx = which(bvsnlp$simulate.cor_type == "independent" & bvsnlp$simulate.censor_lvl == censor_lvls[i])
  is_effect = unlist(lapply(indx, function(x) bvsnlp$simulate.is_effect[[x]]))
  pip.susie = unlist(lapply(indx, function(x) susie$susie.pip[[x]]))
  pip.survsvb = unlist(lapply(indx, function(x) survsvb$svb.pip[[x]]))
  pip.bvsnlp = unlist(lapply(indx, function(x) bvsnlp$bvsnlp.pip[[x]]))
  pip.rss = unlist(lapply(indx, function(x) rss$susie_rss.pip[[x]]))
  pip.r2b = unlist(lapply(indx, function(x) r2b$r2b.pip[[x]]))
  
  # Calibration plot for pip.susie
  calibration.susie = pip_calibration(pip.susie, is_effect)
  plot_calibration(calibration.susie, main = paste0("susie: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.svb
  calibration.survsvb = pip_calibration(pip.survsvb, is_effect)
  plot_calibration(calibration.survsvb, main = paste0("svb: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.bvsnlp
  calibration.bvsnlp = pip_calibration(pip.bvsnlp, is_effect)
  plot_calibration(calibration.bvsnlp, main = paste0("bvsnlp: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.rss
  calibration.rss = pip_calibration(pip.rss, is_effect)
  plot_calibration(calibration.rss, main = paste0("rss: censor=", censor_lvls[i]))
  
  # Calibration plot for pip.r2b
  calibration.r2b = pip_calibration(pip.r2b, is_effect)
  plot_calibration(calibration.r2b, main = paste0("r2b: censor=", censor_lvls[i]))
}
```
