---
title: "SPAcox"
author: "Yunqi Yang"
date: "9/11/2023"
output: html_document
---

```{r}
library(SPACox)
library(survival)
```

```{r}
# Simulation phenotype and genotype
set.seed(1)
N = 1e3
nSNP = 3
MAF = 0.1
Phen.mtx = data.frame(ID = paste0("IID-",1:N),
                      event=rbinom(N,1,0.5),
                      time=runif(N),
                      Cov1=rnorm(N),
                      Cov2=rbinom(N,1,0.5))

# First two SNPs with cor = 1
x1 = rnorm(N)
x2 = x1 + rnorm(N, sd = 1)
Geno.mtx = matrix(c(x1, x1, x2),N,nSNP)
cor(Geno.mtx)

# NOTE: The row and column names of genotype matrix are required.
rownames(Geno.mtx) = paste0("IID-",1:N)
colnames(Geno.mtx) = paste0("SNP-",1:nSNP)
```

```{r}
# Attach the survival package so that we can use its function Surv()
t1 = proc.time()
obj.null = SPACox_Null_Model(Surv(time,event)~Cov1+Cov2, data=Phen.mtx,
                             pIDs=Phen.mtx$ID, gIDs=rownames(Geno.mtx))
SPACox.res = SPACox(obj.null, Geno.mtx)
t2 = proc.time()

t2 - t1


# The below is an example code to use survival package
t1 = proc.time()
coxph(Surv(time,event)~Cov1+Cov2+Geno.mtx, data=Phen.mtx)
t2 = proc.time()

t2 - t1
```

```{r}
# we recommand using column of 'p.value.spa' to associate genotype with time-to-event phenotypes
head(SPACox.res)
```

```{r}
coxph(Surv(time,event)~Cov1+Cov2+Geno.mtx[,1], data=Phen.mtx)
coxph(Surv(time,event)~Cov1+Cov2+Geno.mtx[,3], data=Phen.mtx)
```

