---
title: "assess_cs"
output: html_document
date: '2024-04-15'
---

```{r}
get_mean_abs_corr <- function(res.cs, dat_indx){
  res.mac <- sapply(dat_indx, function(i) {
  if (!is.null(res.cs[[i]])) {
    return(res.cs[[i]]$purity$mean.abs.corr)
  } else {
    return(NULL)
  }
})
  return(unlist(res.mac))
}
```

```{r}
source("./code/post_summary.R")
```

### 1. Small data (GTEx)
```{r}
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim2024/sim_default_iter/susie.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim2024/sim_default_iter/rss.rds")
```

```{r}
pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/cs_gtex.pdf", width = 10, height = 6)
par(mfrow = c(2,3))
# 1. coverage of cs
coverage = matrix(NA, nrow = 2, ncol = 3)
rownames(coverage) = c("susie", "susie.rss")
colnames(coverage) = c("effect:1", "effect:2", "effect:3")
for (i in 1:3) {
  dat_indx = which(susie$simulate.num_effect == i)
  coverage[1, i] = calculate_cs_coverage(susie$susie.cs, susie$simulate.is_effect, dat_indx)
  
  dat_indx = which(rss$simulate.num_effect == i)
  coverage[2, i] = calculate_cs_coverage(rss$rss.cs, rss$simulate.is_effect, dat_indx)
}

# 2. power of cs
power_cs = matrix(NA, ncol = 3, nrow = 2)
rownames(power_cs) = c("susie", "susie.rss")
colnames(power_cs) = c("effect:1", "effect:2", "effect:3")

for (i in 1:3){
  dat_indx = which(susie$simulate.num_effect == i)
  cs_effect = get_cs_effect(susie$susie.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) susie$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[1, i] = power
  
  cs_effect = get_cs_effect(rss$rss.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) rss$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[2, i] = power
}

# 3. mean abs correlation
# 1. coverage of cs
mac = matrix(NA, nrow = 2, ncol = 3)
rownames(mac) = c("susie", "susie.rss")
colnames(mac) = c("effect:1", "effect:2", "effect:3")
for (i in 1:3) {
  dat_indx = which(susie$simulate.num_effect == i)
  
  mac[1, i] = mean(get_mean_abs_corr(susie$susie.cs, dat_indx), na.rm = TRUE)
  mac[2, i] = mean(get_mean_abs_corr(rss$rss.cs, dat_indx), na.rm = TRUE)
}



plot(coverage[1, ], pch = 20, ylim = c(min(coverage) - 0.1, 1), col = "darkred", xlab = "number of effect", ylab = "coverage")
points(coverage[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(power_cs[1, ], pch = 20, ylim = c(min(power_cs) - 0.1, max(power_cs) + 0.1), col = "darkred", xlab = "number of effect", ylab = "power of cs")
points(power_cs[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(mac[1, ], pch = 20, ylim = c(0.97, 1), col = "darkred", xlab = "number of effect", ylab = "mean absolute correlation")
points(mac[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))


#### Plot against different censoring levels 
censor_lvls = unique(susie$simulate.censor_lvl)
coverage = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(coverage) = c("susie", "susie.rss")
colnames(coverage) = censor_lvls

power_cs = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(power_cs) = c("susie", "susie.rss")
colnames(power_cs) = censor_lvls

mac = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(mac) = c("susie", "susie.rss")
colnames(mac) = censor_lvls


for (i in 1:length(censor_lvls)) {
  # susie
  dat_indx = which(susie$simulate.censor_lvl == censor_lvls[i])
  coverage[1, i] = calculate_cs_coverage(susie$susie.cs, susie$simulate.is_effect, dat_indx)
  
  cs_effect = get_cs_effect(susie$susie.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) susie$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[1, i] = power
  mac[1, i] = mean(get_mean_abs_corr(susie$susie.cs, dat_indx), na.rm = TRUE)
  
  #susie rss
  dat_indx = which(rss$simulate.censor_lvl == censor_lvls[i])
  coverage[2, i] = calculate_cs_coverage(rss$rss.cs, rss$simulate.is_effect, dat_indx)
  
  cs_effect = get_cs_effect(rss$rss.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) rss$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[2, i] = power
  mac[2, i] = mean(get_mean_abs_corr(rss$rss.cs, dat_indx), na.rm = TRUE)
}


plot(censor_lvls, coverage[1, ], pch = 20, ylim = c(min(coverage) - 0.1, 1), col = "darkred", xlab = "censor level", ylab = "coverage")
points(censor_lvls, coverage[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(censor_lvls, power_cs[1, ], pch = 20, ylim = c(min(power_cs) - 0.1, max(power_cs) + 0.1), col = "darkred", xlab = "censor level", ylab = "power of cs")
points(censor_lvls, power_cs[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(censor_lvls, mac[1, ], pch = 20, ylim = c(0.97, 1), col = "darkred", xlab = "censor level", ylab = "mean absolute correlation")
points(censor_lvls, mac[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))
```


### 2. Large data (UKB)
```{r}
susie = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie.rds")
rss = readRDS("/project2/mstephens/yunqiyang/surv-susie/dsc202401/susie_rss.rds")
censor_lvls = unique(susie$simulate.censor_lvl)
```

```{r}

pdf("/project2/mstephens/yunqiyang/surv-susie/survival-susie/output/cs_ukb.pdf", width = 10, height = 6)
par(mfrow = c(2,3))
# 1. coverage of cs
coverage = matrix(NA, nrow = 2, ncol = 3)
rownames(coverage) = c("susie", "susie.rss")
colnames(coverage) = c("effect:1", "effect:2", "effect:3")
for (i in 1:3) {
  dat_indx = which(susie$simulate.num_effect == i)
  coverage[1, i] = calculate_cs_coverage(susie$susie.cs, susie$simulate.is_effect, dat_indx)
  
  dat_indx = which(rss$simulate.num_effect == i)
  coverage[2, i] = calculate_cs_coverage(rss$susie_rss.cs, rss$simulate.is_effect, dat_indx)
}

coverage

# 2. power of cs
power_cs = matrix(NA, ncol = 3, nrow = 2)
rownames(power_cs) = c("susie", "susie.rss")
colnames(power_cs) = c("effect:1", "effect:2", "effect:3")

for (i in 1:3){
  dat_indx = which(susie$simulate.num_effect == i)
  cs_effect = get_cs_effect(susie$susie.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) susie$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[1, i] = power
  
  dat_indx = which(rss$simulate.num_effect == i)
  cs_effect = get_cs_effect(rss$susie_rss.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) rss$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[2, i] = power
}

power_cs

# 3. mean abs correlation
# 1. coverage of cs
mac = matrix(NA, nrow = 2, ncol = 3)
rownames(mac) = c("susie", "susie.rss")
colnames(mac) = c("effect:1", "effect:2", "effect:3")
for (i in 1:3) {
  dat_indx = which(susie$simulate.num_effect == i)
  mac[1, i] = mean(get_mean_abs_corr(susie$susie.cs, dat_indx), na.rm = TRUE)
  mac[2, i] = mean(get_mean_abs_corr(rss$susie_rss.cs, dat_indx), na.rm = TRUE)
}
mac

### Plot against different number of effects
plot(coverage[1, ], pch = 20, ylim = c(min(coverage) - 0.1, 1), col = "darkred", xlab = "number of effect", ylab = "coverage")
points(coverage[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(power_cs[1, ], pch = 20, ylim = c(min(power_cs) - 0.1, max(power_cs) + 0.1), col = "darkred", xlab = "number of effect", ylab = "power of cs")
points(power_cs[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(mac[1, ], pch = 20, ylim = c(0.97, 1), col = "darkred", xlab = "number of effect", ylab = "mean absolute correlation")
points(mac[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))


#### Plot against different censoring level
censor_lvls = unique(susie$simulate.censor_lvl)
coverage = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(coverage) = c("susie", "susie.rss")
colnames(coverage) = censor_lvls

power_cs = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(power_cs) = c("susie", "susie.rss")
colnames(power_cs) = censor_lvls

mac = matrix(NA, nrow = 2, ncol = length(censor_lvls))
rownames(mac) = c("susie", "susie.rss")
colnames(mac) = censor_lvls


for (i in 1:length(censor_lvls)) {
  # susie
  dat_indx = which(susie$simulate.censor_lvl == censor_lvls[i])
  coverage[1, i] = calculate_cs_coverage(susie$susie.cs, susie$simulate.is_effect, dat_indx)
  
  cs_effect = get_cs_effect(susie$susie.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) susie$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[1, i] = power
  mac[1, i] = mean(get_mean_abs_corr(susie$susie.cs, dat_indx), na.rm = TRUE)
  
  #susie rss
  dat_indx = which(rss$simulate.censor_lvl == censor_lvls[i])
  coverage[2, i] = calculate_cs_coverage(rss$susie_rss.cs, rss$simulate.is_effect, dat_indx)
  
  cs_effect = get_cs_effect(rss$susie_rss.cs, dat_indx, p = 1000)
  is_effect = unlist(lapply(dat_indx, function(x) rss$simulate.is_effect[[x]]))
  power = sum(cs_effect ==1 & is_effect == 1)/sum(is_effect)
  power_cs[2, i] = power
  mac[2, i] = mean(get_mean_abs_corr(rss$susie_rss.cs, dat_indx), na.rm = TRUE)
}

coverage
power_cs
mac

plot(censor_lvls, coverage[1, ], pch = 20, ylim = c(min(coverage) - 0.1, 1), col = "darkred", xlab = "censor level", ylab = "coverage")
points(censor_lvls, coverage[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(censor_lvls, power_cs[1, ], pch = 20, ylim = c(min(power_cs) - 0.1, max(power_cs) + 0.1), col = "darkred", xlab = "censor level", ylab = "power of cs")
points(censor_lvls, power_cs[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))

plot(censor_lvls, mac[1, ], pch = 20, ylim = c(0.97, 1), col = "darkred", xlab = "censor level", ylab = "mean absolute correlation")
points(censor_lvls, mac[2, ], pch = 20, col = "blue")
legend("bottomleft", legend = c("susie", "susie.rss"), pch = c(20, 20), col = c("darkred", "blue"))
```
