---
title: "Example for susie poor behavior"
author: "Yunqi Yang"
date: "4/10/2023"
output: html_document
---


```{r knitr, echo=FALSE}
knitr::opts_chunk$set(comment = "#",results = "hold",collapse = TRUE,
                      fig.align = "center", warning = FALSE)
```


```{r}
res = readRDS("./data/simulate_380.rds")
```

```{r}
res$effect_size
res$effect_indx
```

```{r}
maf = apply(res$dat$X, 2, function(x) sum(x)/2/length(x))
rs = cor(res$dat$X)
rs[lower.tri(rs, diag = TRUE)] <- NA
range(maf)
range(rs, na.rm = TRUE)
```

```{r}
library(survival)
source("./code/surv_susie_helper.R")
devtools::load_all("/Users/nicholeyang/Desktop/logisticsusie/R")
```

### Run susie
```{r}
#### parameter settings
L = 1
p = ncol(res$dat$X)
maxiter = 1e3
```

```{r}
## Create  survival object
y <- Surv(res$dat$y[,1], res$dat$y[,2])
X = as.matrix(res$dat$X)

fit_coxph <- ser_from_univariate(surv_uni_fun)
fit <- ibss_from_ser(X, y, L = 1, prior_variance = 1., prior_weights = rep(1/p, p), tol = 1e-3, maxit = maxiter, estimate_intercept = TRUE, ser_function = fit_coxph)

pip <- logisticsusie:::get_pip(fit$alpha)
effect_estimate <- colSums(fit$alpha * fit$mu)
sort(pip, decreasing = TRUE)[1:5]
pip[1:5]
```

### Check if any coefficient tends to infinite
```{r}
res.cox = matrix(NA, nrow = p, ncol = 2)
colnames(res.cox) = c("coef", "se")
res.cox = data.frame(res.cox)
for (i in 1:p){
  fit <- coxph(y~ X[,i])
  res.cox[i, ] = summary(fit)$coef[, c(1,3)]
}
range(res.cox$coef)
```

```{r}
fit_coxph <- ser_from_univariate(surv_uni_fun)
fit <- ibss_from_ser(X, y, L = 5, prior_variance = 1., prior_weights = rep(1/p, p), tol = 1e-3, maxit = maxiter, estimate_intercept = TRUE, ser_function = fit_coxph)

pip <- logisticsusie:::get_pip(fit$alpha)
sort(pip, decreasing = TRUE)[1:5]
```

