---
title: "susie.rss diagnosis"
author: "Yunqi Yang"
date: "5/17/2023"
output: html_document
---

```{r}
# Modified Karl's code for intercept part
library(survival)
library(susieR)
library(curl)
devtools::load_all("/Users/nicholeyang/Desktop/logisticsusie")
```

```{r}
get_coxph_sumstats = function(X, y){
  p = ncol(X)
  bhat = rep(NA, p)
  sebhat = rep(NA, p)
  zscore = rep(NA, p)
  for (j in 1:p){
    fit = coxph(y ~ X[ ,j])
    bhat[j] = summary(fit)$coefficients[1, 1]
    sebhat[j] = summary(fit)$coefficients[1, 3]
    zscore[j] = summary(fit)$coefficients[1, 4]
  }
  return(list(bhat = bhat, sebhat = sebhat, zscore = zscore))
}
```

```{r}
dat = readRDS("./data/simulate_3823.rds")
dat2 = readRDS("./data/simulate_3855.rds")
```


```{r}
y <- Surv(dat$dat$y[,1], dat$dat$y[,2])
X = as.matrix(dat$dat$X)

n = nrow(X)
R = cor(X)
sumstats = get_coxph_sumstats(X, y)
z_scores = sumstats$bhat/sumstats$sebhat

lambda = estimate_s_rss(z_scores, R, n=n)
lambda
```

```{r}
susie_plot(z_scores, y = "z", b=dat$b)
condz_in = kriging_rss(z_scores, R, n=n)
condz_in$plot
sort(abs(condz_in$conditional_dist$z - condz_in$conditional_dist$condmean), decreasing = TRUE)[1:5]
```

```{r}
y <- Surv(dat2$dat$y[,1], dat2$dat$y[,2])
X = as.matrix(dat2$dat$X)

n = nrow(X)
R = cor(X)
sumstats = get_coxph_sumstats(X, y)
z_scores = sumstats$bhat/sumstats$sebhat

lambda = estimate_s_rss(z_scores, R, n=n)
lambda
```

```{r}
susie_plot(z_scores, y = "z", b=dat2$b)
condz_in = kriging_rss(z_scores, R, n=n)
condz_in$plot
sort(abs(condz_in$conditional_dist$z - condz_in$conditional_dist$condmean), decreasing = TRUE)[1:5]
```
