---
title: "time comparison"
author: "Yunqi Yang"
date: "9/11/2023"
output: html_document
---

```{r}
dat = readRDS("./data/sim_dat_censoring.rds")
library(BVSNLP)
library(survival)
# Modified Karl's code for intercept part
devtools::load_all("/Users/nicholeyang/Desktop/logisticsusie")
```


```{r} 
# Susie helper functions
# Function to calculate approximate BF based on Wakefield approximation
# @param z: zscore of the regression coefficient
# @param s: standard deviation of the estimated coefficient
compute_abf <- function(z, s, prior_variance){
  abf <- sqrt(s^2/(s^2+prior_variance))*exp(z^2/2*(prior_variance/(s^2+prior_variance)))
  return(abf)
}


compute_approx_post_var <- function(z, s, prior_variance){
  post_var <- 1/(1/s^2 + 1/prior_variance)
  return(post_var)
}

# @param post_var: posterior variance
# @param s: standard deviation of the estimated coefficient
# @param bhat: estimated beta effect
compute_approx_post_mean <- function(post_var, s, bhat){
  mu <- post_var/(s^2)*bhat
  return(mu)
}

surv_uni_fun <- function(x, y, o, prior_variance, estimate_intercept = 0, ...){
  fit <- coxph(y~ x + offset(o))
  bhat <- summary(fit)$coefficients[1, 1] # bhat = -alphahat
  sd <- summary(fit)$coefficients[1, 3]
  zscore <- bhat/sd
  bf <- compute_abf(zscore, sd, prior_variance)
  var <- compute_approx_post_var(zscore, sd, prior_variance)
  mu <- compute_approx_post_mean(var, sd, bhat)
  lbf <- log(bf)
  return(list(mu = mu, var=var, lbf=lbf, intercept=0))
}

fit_coxph <- ser_from_univariate(surv_uni_fun)

```

```{r}
# IBSS of susie
set.seed(1)
p = 50
dat[[1]]$y <- with(dat[[1]], Surv(surT, status))
X = as.matrix(dat[[1]][, c(2:(p+1))])
y = dat[[1]]$y

t1 = proc.time()
fit1 <- ibss_from_ser(X, y, L = 2, prior_variance = 1., prior_weights = rep(1/p, p), tol = 1e-3, maxit = 10, estimate_intercept = TRUE, ser_function = fit_coxph)
t2 = proc.time()

time.susie = t2 - t1
```

```{r}

p = 50
X = as.data.frame(dat[[1]][, c(2:(p+1))])

t1 = proc.time()
fit = bvs(X, resp = y, prep = FALSE, family = "survival", mod_prior = "beta", niter = 10)
t2 = proc.time()

time.bvsnlp1 = t2 - t1


t1 = proc.time()
fit = bvs(X, resp = y, prep = FALSE, family = "survival", mod_prior = "beta", niter = 100)
t2 = proc.time()

time.bvsnlp2 = t2 - t1
```

```{r}
time.bvsnlp1
time.bvsnlp2
time.susie
```

