---
title: "Running time benchmark"
output: html_document
date: '2024-04-02'
---

### Description: time comparison between small and large data

1. Small data (n ~ 500) vs. Large data (n = 50000)

(1) Susie: maxiter = 100 vs. maxiter = 10

(2) BVSNLP: niter = 30

(3) survival.svb: maxiter = 1000 vs. maxiter = 100

(4) susie.rss: maxiter = 100

(5) r2b: niter = 1e6. 

```{r}
time.gtex = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_gtex_default_iter/time_comparison.rds")
time.ukb = readRDS("/project2/mstephens/yunqiyang/surv-susie/sim202406/sim_ukb_niter10/time_comparison.rds")
```

```{r }
t_mean.gtex <- unlist(lapply(1:length(time.gtex),
                    function (i) {
                      res <- subset(time.gtex[[i]],cor_type = "real")
                      return(mean(res[,5],na.rm = TRUE))
                    }))


t_mean.ukb <- unlist(lapply(1:length(time.ukb),
                    function (i) {
                      res <- subset(time.ukb[[i]],cor_type = "real")
                      return(mean(res[,5],na.rm = TRUE))
                    }))
```


```{r}
res = rbind(t_mean.gtex, t_mean.ukb)
colnames(res) = c("susie", "bvsnlp", "susie.rss", "svb", "r2b")
rownames(res) = c("gtex", "ukb")
res
```

