---
title: "Variational inference on exponential survival model"
author: "Yunqi Yang"
date: "3/23/2023"
output: html_document
---

###  1. Model:
$$
\begin{split}
b&\sim N(0, \sigma^2)\\
h(t)&=h_0(t)\exp\{bx\}\\
\end{split}
$$
And we assume $h_0(t) =h_0$, constant baseline hazard and independent censoring. $y_i=\min(t_i,c_i)$, and $\delta_i$ indicates censoring status. $\delta_i=1$: the event time is observed and $\delta_i=0$ indicates censoring. 

```{r}
library(survival)
source("./code/VI_exponential.R")
```


###  2. data simulation 

$$
\begin{split}
S(t)&=\exp\{-h(t)*t\}\\
F(t)&=1-S(t)\sim U[0,1]\\
\end{split}
$$
Using this relationship, we can simulate $t_i$ by:
$$
\begin{split}
t_i=\log(1-u_i)/(-h_0\exp\{bx_i\})
\end{split}
$$
Check if the data simulation makes sense
```{r}
set.seed(1)
n = 1e4
censoring_lvl = 0
s2 = 1 #prior variance of b
h0 = 2
b = rnorm(1, mean = 0, sd = s2)
print(b)
```
```{r}
seeds  = c(1:100)
bhat = rep(NA, 100)

for (seed in seeds){
  x = rnorm(n, 1)
  y <- log(1 - runif(n)) / (-h0*exp(x*b))
  # Status variable delta. delta = 1, outcome observed. delta = 0, censored. 
  d = rbinom(n, size = 1, prob = 1-censoring_lvl)
  y[!d] <- y[!d] * runif(sum(!d))	
  y.surv <- Surv(y, d)
  cox1 <- coxph(y.surv ~ x)
  bhat[seed] = coef(cox1)[1]
}

```

```{r}
hist(bhat)
abline(v = mean(bhat), col = "red")
abline(v = b, col = "blue")
```

### 3. Run variational approximation
```{r}
# change parameter init vals
# the first param is m, the second is v2.
lower = c(-100, 1e-12)
upper = c(100, 100)
res1 <- update_q(x, y, d, h0 = 2, m = 1, v2 = 1, s2 = 1, maxiter = 100, tol = 0.1, lower, upper)
head(res1)
tail(res1)
```

```{r}
# change parameter init vals
lower = c(-100, 1e-12)
upper = c(100, 100)
res2 <- update_q(x[1:20], y[1:20], d[1:20], h0 = 10, m = 1, v2 = 1, s2 = 50, maxiter = 50, tol = 0.1, lower, upper)
head(res2)
tail(res2)
```



